### ISSUE TITLE
[BUG] /iareload console error

### ISSUE THREAD

**Issue by Fargus5** [LoneDev6/ItemsAdder#224] opened 2020-05-12 18:14 UTC
**Describe the bug**
`[20:10:23]: [INFO] Fargus issued server command: /iareload
[20:10:23]: [INFO] Found resourcepack folder: /home/gameserver/servers/serveur6/minecraft/plugins/ItemsAdder/data/resource_pack
[20:10:23]: [INFO] [ItemsAdder] Resourcepack initialization...
[20:10:23]: [INFO] [ItemsAdder] Checking for online default resourcepack updates...
[20:10:23]: [INFO] [ItemsAdder] All worlds: saved 0 regions
[20:10:23]: [INFO] [ItemsAdder] Saved 3 player stats files
[20:10:23]: [INFO] [ItemsAdder] Found cached default resourcepack
[20:10:23]: [INFO] Extracting resources from default resourcepack
[20:10:23]: [INFO] DONE extracting resources from default resourcepack
[20:10:23]: [INFO] - Extracting default items from .jar
[20:10:23]: [INFO] - DONE extracting default items from .jar
[20:10:24]: [INFO] Used 558/13216 available max font images.
[20:10:24]: [INFO] [EpicBackpacks] ItemsAdder finished loading, now loading backpacks...
[20:10:24]: [INFO] [EpicBackpacks] Loaded backpacks correctly
[20:10:24]: [INFO] Loaded 573 items
[20:10:24]: [INFO] Used 117/191 REAL block IDs.
[20:10:24]: [INFO] [ItemsAdder] Checking resourcepack url... http://www.survivalla.fun/respack/pack6.zip
[20:10:24]: [WARN] [ItemsAdder] Plugin ItemsAdder v2.0.22 generated an exception while executing task 2478505
java.lang.NullPointerException: null
at dev.lone.itemsadder.d.e.a(SourceFile:107) ~[?:?]
at dev.lone.itemsadder.d.b.a.f.a(SourceFile:129) ~[?:?]
at dev.lone.itemsadder.d.b.b.b.y(SourceFile:139) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-226]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-226]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
at java.lang.Thread.run(Thread.java:834) [?:?]
[20:10:24]: [INFO] [ItemsAdder] Resourcepack URL is valid. Type: application/zip
[20:10:26]: [INFO] Loaded 40 categories (ia_gui.yml)
[20:10:26]: [INFO] [ItemsAdder] Loaded items and stuff in 2358ms
[20:10:35]: [WARN] Can't keep up! Is the server overloaded? Running 6897ms or 137 ticks behind`

**To Reproduce**
1. Go to 'minecraft in game'
2. Click on '/reload'
3. See te console

**Expected behavior**
I'm modifing the attack damage value of each sword, ad I did the /iareload command to set the update. This one has been successfully updated, but I just see this error in console

**Info (please complete the following information):**
 - Server version: (paper 1.15.2)
 - Plugin version: ("latest")

**Comment by Kerchak3** [comment] 2020-05-16 09:29
Same here, Describe the bug : 
[11:25:30]: [INFO] OhFlyz issued server command: /iareload
[11:25:30]: [ERROR] null
org.bukkit.command.CommandException: Unhandled exception executing command 'iareload' in plugin ItemsAdder v2.0.21
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.2.jar:git-Paper-260]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-260]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:760) ~[patched_1.15.2.jar:git-Paper-260]
at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1852) ~[patched_1.15.2.jar:git-Paper-260]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1660) ~[patched_1.15.2.jar:git-Paper-260]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-260]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-260]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-260]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-260]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-260]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-260]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-260]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1093) ~[patched_1.15.2.jar:git-Paper-260]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1086) ~[patched_1.15.2.jar:git-Paper-260]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-260]
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1047) ~[patched_1.15.2.jar:git-Paper-260]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962) ~[patched_1.15.2.jar:git-Paper-260]
at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
at dev.lone.itemsadder.d.b.b.b.s(SourceFile:192) ~[?:?]
at dev.lone.itemsadder.c.k.onCommand(SourceFile:34) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-260]
... 17 more
[11:25:30]: [INFO] [ItemsAdder] All worlds: saved 0 regions
[11:25:30]: [INFO] [ItemsAdder] Saved 0 player stats files

Expected behavior
Actually, I don't have any item with a modified attribute.

Info :
Server version : (paper 1.15.2)
Plugin version: ("latest")

**Comment by LoneDev6** [comment] 2020-05-18 09:39
This will be fixed in next update, thanks

**Closed by LoneDev6** 2020-05-18 09:39 UTC
Labels: bug
