### ISSUE TITLE
[BUG] Turquoise and Aqua Aura Ore to Diamond Mineral

### ISSUE THREAD

**Issue by Deathroner** [LoneDev6/ItemsAdder#177] opened 2020-04-25 04:08 UTC
The bug is presented that certain blocks that are passed through the furnace, become original minerals of the game.
For example the turquoise ore and the Aqua Aura ore turns into a diamond when passing it through the furnace.

I leave all the evidence here in a link by imgur for you to review. I will leave OP on my server in case you want to try.

[https://imgur.com/a/MrvEx3o](url)

OP: LoneDev

IP: mc.latincrafters.net

**Comment by Deathroner** [comment] 2020-04-25 04:12
Another bug, the mineral blocks turn into mushrooms when broken :(

[https://imgur.com/a/cd0MOzO](url)

**Comment by Deathroner** [comment] 2020-04-25 04:14
> Another bug, the mineral blocks turn into mushrooms when broken :(
> 
> [https://imgur.com/a/cd0MOzO](url)

they also disappear :(

**Comment by LoneDev6** [comment] 2020-04-26 10:41
@Deathroner can I know why you closed that issue after spamming it?
Did you solve it?
Thanks.

**Comment by Deathroner** [comment] 2020-04-26 20:10
I closed it because I thought I had to follow the protocol left by GitHub.

The truth is that it keeps happening

**Comment by D3nied** [comment] 2020-04-26 20:13
yeah i tested it too only with IA on server so no other plugin can modify the outcome but thats defenitly a bug

**Comment by LoneDev6** [comment] 2020-04-26 22:53
> https://imgur.com/a/cd0MOzO

mmhh.. did you get any error in console?
anything? please check in your previous logs as this can happen only if the plugin failed to save regions.

also do you know if you generated these chunks with old versions of the plugin or with 2.0.13? 

Thanks a lot


> https://imgur.com/a/MrvEx3o
I will fix this as soon as possible, thanks

**Comment by Deathroner** [comment] 2020-04-27 03:45
> > https://imgur.com/a/cd0MOzO
> 
> mmhh.. did you get any error in console?

Nothing appears on the console :(

**Comment by LoneDev6** [comment] 2020-04-28 19:20
Thanks, should be fixed in next update.
I will publish the update later, reopen this issue if the problem is still there after 2.0.14

**Closed by LoneDev6** 2020-04-28 19:20 UTC
Labels: bug
