### ISSUE TITLE
Game Crash when loading pack

### ISSUE THREAD

**Issue by drumbo57** [LoneDev6/ItemsAdder#108] opened 2020-03-26 02:05 UTC
When i join the test server of itemsadder. And when i join my test server with items adder. When the pack load my game crash. 
Here the crash file:
https://pastebin.com/i7bgSs5B

**Comment by drumbo57** [comment] 2020-03-26 03:08
My Java version is java update 241 (the last) i tried to remove jvm argument. Without optifine, only vanilla. Delete my 1.15.2 et redownload it and it crash anyway

**Comment by LoneDev6** [comment] 2020-03-26 12:05
What are your PC specs?
Can I also get your client log file? Be sure to send me the log of when your game crashes

**Comment by TheMrLhuixx** [comment] 2020-03-26 17:20
Two friends have the same thing happen to them when they are loading the resource package with ItemsAdder V2, we tried using the V1 version of ItemsAdder with the same resource package and it works without problems ...

**Comment by TheMrLhuixx** [comment] 2020-03-26 17:21
also note apart from us, other people having the same problem

**Comment by LoneDev6** [comment] 2020-03-26 17:22
> 
> 
> Two friends have the same thing happen to them when they are loading the resource package with ItemsAdder V2, we tried using the V1 version of ItemsAdder with the same resource package and it works without problems ...

How did you use the same resource package on V1? They are not compatible each other.
Did you convert it?

**Comment by TheMrLhuixx** [comment] 2020-03-26 17:25
> > Two friends have the same thing happen to them when they are loading the resource package with ItemsAdder V2, we tried using the V1 version of ItemsAdder with the same resource package and it works without problems ...
> 
> How did you use the same resource package on V1? They are not compatible each other.
> Did you convert it?

I had a backup of V1 from my resource pack, then I converted to V2

**Comment by LoneDev6** [comment] 2020-03-26 17:50
Also happens if you join my test server? lonedev.my.pebble.host

**Comment by TheMrLhuixx** [comment] 2020-03-26 17:55
> Also happens if you join my test server? lonedev.my.pebble.host

I will ask my friend to connect to see if he has the same problem

**Comment by TheMrLhuixx** [comment] 2020-03-26 18:20
> Also happens if you join my test server? lonedev.my.pebble.host

I just entered, and the game crashed

**Comment by LoneDev6** [comment] 2020-03-26 18:23
Can you test on another PC?
Can you ask your friend if they applied any other resourcepack? Maybe another pack is making the client crash.
Are they using optifine? Fabric? Forge? custom client?

**Comment by LoneDev6** [comment] 2020-03-26 18:24
Also.. as I asked, please answer:
> What are your PC specs?
> Can I also get your client log file? Be sure to send me the log of when your game crashes

**Comment by TheMrLhuixx** [comment] 2020-03-26 18:33
> Also.. as I asked, please answer:
> 
> > What are your PC specs?
> > Can I also get your client log file? Be sure to send me the log of when your game crashes

log file: https://pastebin.com/J2yscHk7

my friend's pc specs: Processor: Intel (R) Coleron (R) 2981U 1.60GHz
Ram memory: 4 GB
Operating system: Windows 10 64 bit
GPU: Integrated

Obviously it doesn't happen on my computer, it only happens to certain people... but in the V1 version of itemsadder, my friend works well with the resource pack

**Comment by TheMrLhuixx** [comment] 2020-03-26 18:34
> Can you test on another PC?
> Can you ask your friend if they applied any other resourcepack? Maybe another pack is making the client crash.
> Are they using optifine? Fabric? Forge? custom client?

I do not apply any other resource package, I use with Optifine and without Optifine and the same thing happens

**Comment by drumbo57** [comment] 2020-03-27 00:12
i've seen in some topics that is caused by intel graphics card i got
Intel Graphics HD 4400
intel core i7 4500u
8gb ram

yes it's crash with the test server lonedev.my.pebble.host crash, it crash in 1.15 and 1.15.2 (i didn't test 1.14) and in vanilla it crash, with optifine it crash

**Comment by drumbo57** [comment] 2020-03-27 00:14
> What are your PC specs?
> Can I also get your client log file? Be sure to send me the log of when your game crashes

https://pastebin.com/i7bgSs5B it's my game client crash log

**Comment by drumbo57** [comment] 2020-03-27 00:15
and my game never crash in another server, plugins.... it crash only when it has itemsadder v2

**Comment by TheMrLhuixx** [comment] 2020-03-27 03:17
Another friend with the same game crash, he sent me a photo of his specifications https://imgur.com/NLDBeVj

**Comment by LoneDev6** [comment] 2020-03-28 11:40
Can you try to:
- start the game
- put this file in the game resourcepacks folder https://anonfile.com/z4P4e5kbob/test_zip
- open game settings and apply the new resourcepack you downloaded
- start SINGLEPLAYER mode


does it crash?

**Comment by LoneDev6** [comment] 2020-03-28 17:42
Seems the cause of the issue is related to a Minecraft bug about fonts.
Only way to fix this is to
- install ItemsAdder 2.0.5
- set these values in config.yml:

```
  negative-spaces-font:
    enabled: false
```

```
huds:
  enabled: false
```

- [reupload ](https://itemsadder.plugin.ga/how-to-create-items/resourcepack-hosting/resourcepack-on-dropbox)the new generated pack (or if you use selfhost follow [selfhost tutorial](https://itemsadder.plugin.ga/how-to-create-items/resourcepack-hosting/resourcepack-self-hosting))

**Comment by LoneDev6** [comment] 2020-03-28 21:20
@drumbo57 @TheMrLhuixx 
Here's the Mojang answer to my report: https://bugs.mojang.com/browse/MC-176595
They closed it as duplicate of another one which reports that it's an Intel Graphics driver problem and you have to update

**Comment by drumbo57** [comment] 2020-03-28 21:23
yes it's crashing with your ressource pack test.zip @LoneDev6 and my graphic card has the last update driver.

**Comment by LoneDev6** [comment] 2020-03-28 21:28
> 
> 
> yes it's crashing with your ressource pack test.zip @LoneDev6 and my graphic card has the last update driver.

it's really random then, I tested on a friend PC and doesn't crash with the test.zip file but only with ItemsAdder pack and only when I load HUDs or GUIs

**Comment by LoneDev6** [comment] 2020-04-03 09:56
Fixed, it's a Minecraft bug I managed to bypass

**Closed by LoneDev6** 2020-04-03 09:56 UTC
Labels: vanilla bug
