### ISSUE TITLE
[BUG] Search function Broken

### ISSUE THREAD

**Issue by D3nied** [LoneDev6/ItemsAdder#180] opened 2020-04-26 20:25 UTC
**Describe the bug**
Well i think the search function in /ia ia broken i don't get any outcome when i type in book or hammer or something else ^^

**To Reproduce**
1. /ia
2. Click on the search icon
3. search something for example hammer
4. See no search results

**Expected behavior**
Some search results

**Short Video**
https://streamable.com/yrjpw8

**Info (please complete the following information):**
 - Server version: paper 1.15.2 (Build 220)
 - Client version: Optifine Minecraft
 - Plugin version: 2.0.13

**Additional context**
the problem is starting in version 2.0.7 in 2.0.6 Beta the search is working

**Comment by Deathroner** [comment] 2020-04-26 22:55
I confirm, the same thing happens to me

**Comment by LoneDev6** [comment] 2020-04-28 17:20
Thanks, should be fixed in next update.
I will publish the update later, reopen this issue if the problem is still there after 2.0.14

**Closed by LoneDev6** 2020-04-28 17:20 UTC
Labels: bug
