### ISSUE TITLE
[BUG] Recipes not loading sometimes on server start

### ISSUE THREAD

**Issue by 100petr** [LoneDev6/ItemsAdder#260] opened 2020-05-20 17:47 UTC
**Describe the bug**
Errors in console https://pastebin.com/DHWvU47D
Full log: https://pastebin.com/1HBFSLnU

error: https://pastebin.com/zMcNhC0p
full log: https://pastebin.com/mckBMV1s

error: https://pastebin.com/reuD3eQ2
full log: 
[2020-05-23-2.log](https://github.com/LoneDev6/ItemsAdder/files/4671951/2020-05-23-2.log) 

**To Reproduce**
1. Start server
2. See error

**Expected behavior**
no errors

**Screenshots**

**Info (please complete the following information):**
 - Server version: paper 1.15.2
 - Client version: 
 - Plugin version: 2.0.24

**Additional context**

**Comment by LoneDev6** [comment] 2020-05-26 11:39
did you fix? why did you close it?

thanks

**Comment by 100petr** [comment] 2020-05-26 11:43
I forgot that I post here 3 errors. 
Occasionally, for some reason, recipes could not be seen and it gave this error Could not pass event InventoryClickEvent to ItemsAdder v2.0.24
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
Helped /iareload (so far it has happened about three times)

**Comment by LoneDev6** [comment] 2020-06-02 08:23
Please reopen this issue if this problem is not fixed in new update i will publish, thanks

**Comment by 100petr** [comment] 2020-06-07 13:48
Today I got this error again after loading the server https://pastebin.com/fbGyAq0Y
full log: https://pastebin.com/JxqZgXr0

**Comment by LoneDev6** [comment] 2020-06-22 14:06
Do you know when this happens?

**Comment by 100petr** [comment] 2020-06-22 14:08
I don't know if that's it, but sometimes the recipe for an item doesn't show up on the server, just a repair in anvil. It will always help /iareload

**Comment by LoneDev6** [comment] 2020-06-22 14:10
Maybe related https://github.com/LoneDev6/ItemsAdder/issues/295

I'd ignore it if it's not spammy and gameplay breaking

**Comment by 100petr** [comment] 2020-06-22 14:11
What I found was probably not related to those recipes. If don't see the recipes it gives it this https://pastebin.com/RJEH6PLX

**Comment by 100petr** [comment] 2020-06-22 14:12
Ok, I think it's not spamming. It just happens occasionally.

**Comment by LoneDev6** [comment] 2020-06-22 14:39
Does this happens only after the first /iareload?
Maybe it's something to do with plugin reload

**Comment by 100petr** [comment] 2020-06-22 15:05
Recipes sometimes do not appear after a reboot. /iareload fixes this

**Comment by LoneDev6** [comment] 2020-06-22 15:32
You are saying that after you RESTART the server all recipes do not load?
Are you 100% sure?
Did you wait until IA finished loading? It's async

**Comment by 100petr** [comment] 2020-06-22 15:34
Yes, sometimes in the morning after an automatic restart there are no recipes, only a correction.

**Comment by PhanaticD** [comment] 2020-06-23 05:42
yep this breaks recipes

**Comment by 100petr** [comment] 2020-06-24 07:43
After restart server. Error: https://pastebin.com/z40GHGad
![2020-06-24_09 42 29](https://user-images.githubusercontent.com/29830635/85517043-2a593a00-b5ff-11ea-9103-bbe4850996b4.png)
![2020-06-24_09 42 31](https://user-images.githubusercontent.com/29830635/85517047-2af1d080-b5ff-11ea-8082-e46004ed4e95.png)
![2020-06-24_09 42 39](https://user-images.githubusercontent.com/29830635/85517050-2b8a6700-b5ff-11ea-877b-00272e5f0086.png)
![2020-06-24_09 42 46](https://user-images.githubusercontent.com/29830635/85517053-2cbb9400-b5ff-11ea-83f3-46be1af6488c.png)
![2020-06-24_09 42 47](https://user-images.githubusercontent.com/29830635/85517058-2decc100-b5ff-11ea-97d4-6532b2328153.png)

**Comment by 100petr** [comment] 2020-06-24 07:45
After typing /iareload
![2020-06-24_09 44 30](https://user-images.githubusercontent.com/29830635/85517281-655b6d80-b5ff-11ea-9741-cd2146ae1d83.png) it is fixed.

**Comment by LoneDev6** [comment] 2020-06-24 08:59
I think it's because some user joins while ItemsAdder is still loading and clicks on the /ia GUI, this seems to stop the recipes loading process.
I will try to reproduce the issue and fix it today, thanks all

**Comment by LoneDev6** [comment] 2020-06-24 09:52
Should be fixed in the new update, let me know

**Comment by 100petr** [comment] 2020-06-25 17:34
Today I only had a repair in the /ia GUI again.

**Comment by 100petr** [comment] 2020-06-25 17:40
```[19:00:47] [Craft Scheduler Thread - 58/WARN]: [ItemsAdder] Plugin ItemsAdder v2.0.28 generated an exception while executing task 4552
java.util.ConcurrentModificationException: null
     at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:1.8.0_241]
     at java.util.ArrayList$Itr.next(ArrayList.java:859) ~[?:1.8.0_241]
     at dev.lone.itemsadder.e.g.c.c.a(SourceFile:88) ~[?:?]
     at dev.lone.itemsadder.e.g.c.c.b(SourceFile:110) ~[?:?]
     at dev.lone.itemsadder.h.c.a(SourceFile:71) ~[?:?]
     at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-372]
     at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-372]
     at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-372]
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_241]
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_241]
     at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]```

**Comment by 100petr** [comment] 2020-06-26 05:36
Today again. And I connected until a few minutes after starting the server https://pastebin.com/ev22JqNC

**Comment by LoneDev6** [comment] 2020-06-26 16:07
Thanks, I added more checks for this in the new update, I hope this will fix the issue.
Try the new update when I will release it: 2.0.29

**Comment by 100petr** [comment] 2020-06-27 09:15
Today again with IA 2.0.29

**Comment by LoneDev6** [comment] 2020-06-27 09:23
Send me the error again, maybe it's another part of the code now.
Thanks, I hope to manage to fix this as I cannot reproduce the issue

**Comment by 100petr** [comment] 2020-06-27 09:32
No errors
```[08:47:13] [Craft Scheduler Thread - 41/INFO]: [ItemsAdder] Checking resourcepack url... http://82.208.17.29:31368/pack.zip
[08:47:13] [Craft Scheduler Thread - 43/INFO]: [ItemsAdder] Resourcepack URL should be valid. using self-host. Url: http://82.208.17.29:31368/pack.zip
[08:47:13] [Craft Scheduler Thread - 41/INFO]: Loaded 36 categories (ia_gui.yml)
[08:47:13] [Craft Scheduler Thread - 41/INFO]: [ItemsAdder] Loaded items and stuff in 19957ms``` Full server log: https://pastebin.com/fqxgiUS1

**Comment by LoneDev6** [comment] 2020-06-27 09:45
No errors but the recipes didn't load?

**Comment by 100petr** [comment] 2020-06-27 09:47
Yes..

so 27. 6. 2020 v 11:45 odesílatel LoneDev <notifications@github.com> napsal:

**Comment by 100petr** [comment] 2020-06-28 04:57
![2020-06-28_06 52 52](https://user-images.githubusercontent.com/29830635/85938328-9fcd4f00-b90c-11ea-8d8b-80199f732f54.png)
![2020-06-28_06 53 23](https://user-images.githubusercontent.com/29830635/85938329-a0fe7c00-b90c-11ea-8df4-021248c06066.png)
[latest.log](https://github.com/LoneDev6/Issues-ItemsAdder/files/4841709/latest.log)

**Comment by LoneDev6** [comment] 2020-06-29 10:08
I have to investigate more on this, that's really strange as I can't reproduce the issue on my test servers, sorry for the inconvenience

**Comment by LoneDev6** [comment] 2020-06-30 09:14
So now NO ERROR is shown but ALL crafting/smelting recipes are not loaded?
Only anvil repair recipes are loaded correctly, right?

**Comment by 100petr** [comment] 2020-06-30 09:22
Yes. But it only happens occasionally (not always)

út 30. 6. 2020 v 11:14 odesílatel LoneDev <notifications@github.com> napsal:

**Comment by LoneDev6** [comment] 2020-06-30 09:37
I have to find the cause.. mhhh I really have no idea, do you think this happens if a user joins while the plugin is loading?
Something like that?

I have no clue

**Comment by 100petr** [comment] 2020-06-30 09:39
Well, once I sent a log here, when the first player joined after maybe about 6 minutes.

**Comment by LoneDev6** [comment] 2020-07-02 10:28
this error log is from 2.0.28, so in 2.0.31 there is no error but the problem is still there.
I can tell that the error was not related to the issue then.. this is even more difficult to debug

**Comment by 100petr** [comment] 2020-07-20 16:42
Hi, my server from 1.7. is on 1.16.1 and I haven't encountered it since. Maybe it's some 1.15.2 problem that's in 1.16.1 fixed?

**Comment by LoneDev6** [comment] 2020-07-21 12:00
I have no idea, I've never succeed into reproducing the issue on 1.15.2, it would be a Spigot bug which now is fixed

**Comment by 100petr** [comment] 2020-08-01 08:48
So unfortunately, it happened again today.

**Comment by 100petr** [comment] 2020-08-28 17:56
Can't this have something to do with the problem? (that it interrupts some other server plugin) https://hub.spigotmc.org/jira/browse/SPIGOT-6084

**Comment by LoneDev6** [comment] 2020-08-30 10:21
> 
> 
> Can't this have something to do with the problem? (that it interrupts some other server plugin) https://hub.spigotmc.org/jira/browse/SPIGOT-6084

Oh damn this is bad, I hope they fix it, it could definitely be the cause of this bug

**Comment by 100petr** [comment] 2020-08-30 10:24
https://github.com/PaperMC/Paper/issues/4244
it was also reported on paper yesterday.

**Comment by LoneDev6** [comment] 2020-09-08 09:46
Mhhhh.. well I could make a task that checks for recipes every 15 minutes and reloads them if no recipe is found, would it be good?
It's a bit hacky but that's the only way I think

**Comment by 100petr** [comment] 2020-09-08 09:51
It sounds good, but it might be enough to reload them a few minutes after rebooting.

**Comment by LoneDev6** [comment] 2020-09-08 10:01
Basically seems that somehow something is unloading my recipes (and also other plugins ones?) after some gameplay minutes, right?
I think we need to find out the cause, this hacky patch smells a bit and I fear it could deal to problems

**Comment by 100petr** [comment] 2020-09-08 10:07
I'd say something cancels loading those recipes completely. It occurs to me that now it happens with each reboot, so I could try looking for a plugin that does it. Before it was only occasionally, it would be hard to find.Odesláno z mého chytrého telefonu Samsung Galaxy.

**Comment by LoneDev6** [comment] 2020-09-08 10:36
Can you try these two things?

- firstly try with normal Spigot, no fork, no Paper: https://serverjars.com/api/fetchJar/spigot/1.16.2

- second test (after some days) try to schedule /iareload command to be executed on each server restart after 5 minutes and see if the recipes are always available after this hotfix


Thanks for all the info

**Comment by LoneDev6** [comment] 2020-10-02 15:34
I will close this issue as I didn't get any new report about this.
Thanks all for the patience

**Closed by LoneDev6** 2020-10-02 15:34 UTC
Labels: HIGH PRIORITY, bug

**Comment by 100petr** [comment] 2020-10-02 15:44
The server was on spigot for a while, but it was terribly choppy. So I had to return it. It's still happening, but there's probably nothing left but to check it and give iareload.

**Comment by LoneDev6** [comment] 2020-10-02 15:56
Do you have any datapack installed?

**Comment by 100petr** [comment] 2020-10-02 16:05
![image](https://user-images.githubusercontent.com/29830635/94944569-ba99fb80-04d9-11eb-9fbb-ba3e937b23ce.png)
As far as I know, this is for every server.

**Comment by LoneDev6** [comment] 2020-10-03 15:47
I doubt it has something to do with the default bukkit datapack, strange.

Well there is something which is cleaning up my damn recipes, I don't do that myself :( did you try removing some of the plugins in your server?

**Comment by 100petr** [comment] 2020-10-03 15:49
@PhanaticD is it still happening to you? Maybe we could try to compare plugins that we have the same and look for the cause in one of the same plugins.

**Comment by 100petr** [comment] 2020-10-10 15:25
![image](https://user-images.githubusercontent.com/29830635/95658804-7f24b000-0b1d-11eb-9830-dc3301d8a12b.png)
so i will make my own plugin which after launch will give /iareload, still thank you.

**Comment by LoneDev6** [comment] 2020-10-12 09:00
No problem, I still want to find the cause but seems something related to your server configuration and I really have no idea.
I'm happy you found a workaround
