### ISSUE TITLE
Shapeless recipe

### ISSUE THREAD

**Issue by IPECTER** [LoneDev6/ItemsAdder#3423] opened 2024-02-12 07:34 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Countinue-Issue https://github.com/PluginBugs/Issues-ItemsAdder/issues/3417.
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/80433772/c4c63d8a-48eb-40b2-bbca-4553aa40474e)
I think its not limitation of shapeless recipe..
many custom recipe plugin(CustomCrafting, etc..) can make shapeless recipe with duplicated ingredients.
why dont you try implementing it.... plz...
**IA HAS TOO MUCH RECIPE LIMITATION**

### Is your feature request related to a problem?

X

### Describe alternatives you've considered

X

### Additional context

X

**Comment by LoneDev6** [comment] 2024-02-28 15:20
Duplicate of #2831

**Closed as not planned by LoneDev6** 2024-02-28 15:20 UTC
Labels: type: duplicate
