### ISSUE TITLE
[Bug] Chunks data memory leak (NBTFile)

### ISSUE THREAD

**Issue by HolographicWings** [LoneDev6/ItemsAdder#114] opened 2020-04-04 10:26 UTC
Hello i have notice a big memory leak with the NBTTagCompound, i don't understand what is it exactly, but itemsadder user more than 2Gb of RAM
here a memory dump : https://anguloce.ddns.net/heap-dump-2020-04-04_11.08.09.7z

![1](https://user-images.githubusercontent.com/19623115/78424831-4be5fd80-7670-11ea-944b-4ad68ab334fa.JPG)
-----------------------------------------
![2](https://user-images.githubusercontent.com/19623115/78424832-4c7e9400-7670-11ea-9c7a-6dcad64728df.JPG)
-----------------------------------------
![3](https://user-images.githubusercontent.com/19623115/78424833-4c7e9400-7670-11ea-97e0-5cf30051b9a3.JPG)
-----------------------------------------
![4](https://user-images.githubusercontent.com/19623115/78424834-4d172a80-7670-11ea-9940-80e33df13534.JPG)

**Comment by LoneDev6** [comment] 2020-04-04 10:28
How many players do you have connected?
How many chunks loaded? If you have essentials you can use /lag command to read that

**Comment by HolographicWings** [comment] 2020-04-04 10:28
2 players, ~600 chunks

**Comment by LoneDev6** [comment] 2020-04-04 10:29
> 
> 
> 2 players, ~600 chunks

Did you restart the plugin multiple times during gameplay (or /iareload)?

**Comment by HolographicWings** [comment] 2020-04-04 10:30
i never use reload, i always restart the entire server

**Comment by LoneDev6** [comment] 2020-04-04 10:31
So you start the server, travel around and the ram never lower down?

**Comment by HolographicWings** [comment] 2020-04-04 10:33
no, just increases

**Comment by LoneDev6** [comment] 2020-04-04 10:33
Are the chunk coords you see in the screen related to where you are or to an unloaded chunk?
![immagine](https://user-images.githubusercontent.com/27242001/78424829-4a1c3a00-7670-11ea-9b78-823429cf9109.png)
https://dinnerbone.com/minecraft/tools/coordinates/
for example the first is "This region contains blocks -27648,0,15360 to -27137,255,15871"

**Comment by HolographicWings** [comment] 2020-04-04 10:34
i don't know

**Comment by LoneDev6** [comment] 2020-04-04 10:35
Thanks for the info, I will make some tests.
I think it's because somehow my data regions won't get unloaded correctly, I'll address this issue in 2 days, I hope you can wait.
Maybe it's a bug of the library I use to manage NBT files.

Sorry for the inconvenience

**Comment by HolographicWings** [comment] 2020-04-04 10:35
no worry, and thanks you for your instant answer x')

**Comment by LoneDev6** [comment] 2020-04-06 12:25
I close this issue, please reopen it if the issue is not solved in the next update 2.0.8

**Closed by LoneDev6** 2020-04-06 12:25 UTC
Labels: HIGH PRIORITY, bug

**Comment by LoneDev6** [comment] 2020-04-14 14:30
@HolographicWings let me know ;)
