### ISSUE TITLE
[BUG] Generated model does not link "west" side

### ISSUE THREAD

**Issue by Golshr** [LoneDev6/ItemsAdder#157] opened 2020-04-18 13:10 UTC
**Describe the bug**
When I put several textures on the "resource.textures" and i'm looking into the generated models, the west side of the block is missing.

**To Reproduce**
Here is a part of my yml file which contain my blocks declaration : 

>   block_faces_test:
>     display_name: block_faces_test
>     resource:
>       material: STONE
>       generate: true
>       textures:
>       - blocks/block_faces_test/1.png
>       - blocks/block_faces_test/2.png
>       - blocks/block_faces_test/3.png
>       - blocks/block_faces_test/4.png
>       - blocks/block_faces_test/5.png
>       - blocks/block_faces_test/6.png
>     specific_properties:
>       block:
>         placed_model:
>           type: TILE
>           break_particles: BLOCK

And here is the generated model : 

> {
>   "parent": "block/base/block_tile",
>   "textures": {
>     "down": "test:blocks/block_faces_test/1",
>     "east": "test:blocks/block_faces_test/6",
>     "north": "test:blocks/block_faces_test/3",
>     "south": "test:blocks/block_faces_test/4",
>     "up": "test:blocks/block_faces_test/5",
>     "particle": "test:blocks/block_faces_test/1"
>   }
> }

As you can see, the "west" texture is missing (all texture files are at the right place)

**Expected behavior**
West is supposed to be here. By the way, the deduced faces order looks strange : down, west, north, south, up, east... Is it normal ?

**Info (please complete the following information):**
 - Server version: Spigot 1.15.2
 - Client version: Vanilla 1.15.2
 - Plugin version: v2.0.9

**Comment by LoneDev6** [comment] 2020-04-20 13:46
Thanks, should be fixed in next update.
I will publish the update later, reopen this issue if the problem is still there after 2.0.13

**Closed by LoneDev6** 2020-04-20 13:46 UTC
Labels: bug
