### ISSUE TITLE
Replace armorstands with display item / block for version 1.19.4+

### ISSUE THREAD

**Issue by PanHaskins** [LoneDev6/ItemsAdder#2980] opened 2023-08-30 13:12 UTC
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

panhaskins

### Describe the solution you'd like

Although someone already suggested it in the Discord chat, probably nobody noticed it, that's why I'm writing here after a long time. Since 1.19.4 Mojang has made a very optimized, AI-free, new entity that is quite a bit better than armorstands.
It's a Display Block and Item Display. Display Block could be used for Custom Blocks, although it probably wouldn't be more optimized than the current feature that is there but Item Display could be used nicely for furniture for example. The furniture in question could also be enlarged to any size without any problems. Basically just replacing ArmorStands with Item Display, which is more optimized.

### Is your feature request related to a problem?

Compatibility issue with different versions of minecraft. It would only have to support 1.19.4 and above.

### Describe alternatives you've considered

There is probably no alternative to this request. Unless everything was left to the armorstands.

### Additional context

https://minecraft.fandom.com/wiki/Java_Edition_1.19.4

**Comment by LoneDev6** [comment] 2023-09-03 15:00
> 1.19.4 Mojang has made a very optimized, AI-free, new entity that is quite a bit better than armorstands.

I did some benchmarks back when they released the feature and the performance improvement wasn't really huge to justify implementing that.
Anyway it's planned for the future :D

Duplicate of https://github.com/PluginBugs/Issues-ItemsAdder/issues/2458

**Closed as not planned** 2023-10-09 16:06 UTC
Labels: type: duplicate
