### ISSUE TITLE
[BUG] Jukebox can insert 64 disc

### ISSUE THREAD

**Issue by R-Josef** [LoneDev6/ItemsAdder#156] opened 2020-04-18 09:00 UTC
**Describe the bug**
Jukebox can insert 64 discs, but only 1 can be remove.

**To Reproduce**
1. hand 64 discs, and right click a jukebox
2. all of the disc will be insert
3. then right click again to remove the disc
4. only 1 disc dorp

**Info (please complete the following information):**
 - Server version: tuinity 1.15.2
 - Client version: vanllia 1.15.2
 - Plugin version: 2.0.12

**Comment by LoneDev6** [comment] 2020-04-20 13:48
Thanks, should be fixed in next update.
I will publish the update later, reopen this issue if the problem is still there after 2.0.13

**Closed by LoneDev6** 2020-04-20 13:48 UTC
Labels: bug
