### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Mrkhris** [LoneDev6/ItemsAdder#143] opened 2020-04-16 14:20 UTC
https://pastebin.com/P82VnA5B
https://pastebin.com/i7jcaEDe

This error began to appear when I switched after the last beta version to the latest version of the plugin, what’s wrong, don’t tell me how to fix it?

Spigot 1.15.2
ItemsAdder 2.0.10

**Comment by RustyDagger** [comment] 2020-04-17 00:30
Duplicate of bug #141 and probably related to #148 

Also i'm sure the Dev would appreciate if you followed the bug reporting template in the future. make it easy for them and your more likely to get help.

**Comment by LoneDev6** [comment] 2020-04-17 12:16
Fixed in 2.0.11, reopen this issue if after update you still have problems. I will post the update today.
Thanks for the report.

**Closed by LoneDev6** 2020-04-17 12:16 UTC
Labels: bug
