### ISSUE TITLE
[BUG] Ores spawning in the wrong places

### ISSUE THREAD

**Issue by MelleVM** [LoneDev6/ItemsAdder#171] opened 2020-04-24 12:07 UTC
I'm currently experiencing a bug where the ores don't spawn in the right place, for example if i set an ore to spawn instead of Diamond Ore it will spawn in the place of dirt and stone as well.

Example:

  compressed_diamond_ore:
    block: itemsadder:compressed_diamond_ore
    worlds:
    - world
    replaceable_blocks:
    - DIAMOND_ORE
    chance: 100.0
    max_height: 16
    min_height: 5
    amount: 3
    iterations: 3

**Comment by LoneDev6** [comment] 2020-04-28 15:25
Thanks, should be fixed in next update.
I will publish the update later, reopen this issue if the problem is still there after 2.0.14

**Closed by LoneDev6** 2020-04-28 15:25 UTC
Labels: bug
