### ISSUE TITLE
[BUG] A group of minerals become one after converter.

### ISSUE THREAD

**Issue by R-Josef** [LoneDev6/ItemsAdder#163] opened 2020-04-19 17:00 UTC
**Describe the bug**
1.0 one group minerals become one mineral after 2.0 auto update.

**To Reproduce**
1. In 1.0 put one group minerals like ruby*64 in box
2. Update plugin to 2.0
3. Set items-auto-update inventory-open: true in converter.yml
4. just left one ruby in box(also it become usable in 2.0)

**Screenshots**
![convert](https://fengshuai.oss-cn-shenzhen.aliyuncs.com/%E5%9B%BE%E5%BA%8A/convert.png)
![still work](https://fengshuai.oss-cn-shenzhen.aliyuncs.com/%E5%9B%BE%E5%BA%8A/item_still_work.png)

**Info (please complete the following information):**
 - Server version: tuinity 1.15.2
 - Client version: vanllia
 - Plugin version: 2.0.12

**Comment by LoneDev6** [comment] 2020-04-20 14:00
Thanks, should be fixed in next update.
Sorry for the inconvenience! Please temporary disable converter in converter.yml until I publish the new update.

I will publish the update later, reopen this issue if the problem is still there after 2.0.13

**Closed by LoneDev6** 2020-04-20 14:00 UTC
Labels: bug
