### ISSUE TITLE
Custom blocks turning into mushroom blocks after /iareload

### ISSUE THREAD

**Issue by Mintycraft** [LoneDev6/ItemsAdder#104] opened 2020-03-20 04:08 UTC
So when I place custom blocks in the world, they show up and seem to work just fine at first.
![2020-03-19 21_01_00-Window](https://user-images.githubusercontent.com/52329037/77134732-83746900-6a25-11ea-89a0-26648c45a3a9.png)
However once I run /iareload, any custom blocks I have in the world will either slowly turn into mushroom blocks over time, or if I break a custom blocks, all the ones that previously touched it will be mushroom blocks as well.
![2020-03-19 21_02_28-Window](https://user-images.githubusercontent.com/52329037/77134786-bc144280-6a25-11ea-912e-0e0c13fe0916.png)

**Comment by LoneDev6** [comment] 2020-03-20 11:21
I will post an update today, please let me know if fixes the issue.
Thanks a lot!
Reopen this if not fixed

**Comment by Mintycraft** [comment] 2020-03-21 03:33
So far as of 2.0.3, it is not happening anymore. Thank you!

**Comment by Mintycraft** [comment] 2020-03-27 18:55
Unfortunately, the issue has returned in 2.0.4.

**Comment by LoneDev6** [comment] 2020-03-28 11:52
> 
> 
> Unfortunately, the issue has returned in 2.0.4.

Only on /iareload ?
Strange as I didn't edit anything in the plugin

**Comment by Mintycraft** [comment] 2020-03-28 23:10
On /iareload, when reloading with PlugMan, or if the server is stopped and started again. I reverted to 2.0.3, and it fixes it. 2.0.3 reloading doesn't cause them to turn into mushroom blocks.

**Comment by LoneDev6** [comment] 2020-03-30 16:25
Really strange..
are you 100% sure? do you get any error in console on /iareload?

Sorry for dumb questions but I have to be sure since I don't have this issue

**Comment by Mintycraft** [comment] 2020-03-31 07:42
![image](https://user-images.githubusercontent.com/52329037/77999642-e00a3a80-72e7-11ea-9b40-fe0c49074b0d.png)

Console seems fine. This is 2.0.6, and the problem still shows up. I don't have any plugins that do anything unusual with mushroom blocks.

**Comment by LoneDev6** [comment] 2020-04-03 10:39
Is it a test server?
If you can, please 
- break all custom blocks
- stop server
- delete the content of: plugins\ItemsAdder\storage\regions_data
- start server
- place blocks
- /iareload
- try to break blocks and see if they are bugged

**Comment by Mintycraft** [comment] 2020-04-04 00:52
I was able to do all of that, and so far they seem to be staying as they should now. Should I clean that folder out upon updating the plugin from now on?

**Comment by LoneDev6** [comment] 2020-04-06 10:32
nono, don't clean the folder anymore, I think that it contained some corrupted data or something like that.
This folder contains every custom block data in the world, so don't delete it anymore

**Comment by LoneDev6** [comment] 2020-04-06 10:33
So is the issue fixed? :D

**Comment by Mintycraft** [comment] 2020-04-09 06:36
Sorry for the late response. It was fixed until I updated to 2.0.9 earlier today. Any blocks placed and removed after the update are fine, on reload, but anything that was placed before the update eventually changed back to mushroom blocks.

**Comment by LoneDev6** [comment] 2020-04-09 11:31
> 
> 
> Sorry for the late response. It was fixed until I updated to 2.0.9 earlier today. Any blocks placed and removed after the update are fine, on reload, but anything that was placed before the update eventually changed back to mushroom blocks.

So basically:
when everytime you update old placed blocks broke? And it's not about /iareload anymore?
Are you sure there is no itemsadder error in console at anytime?
Surely there's something strange happening on the server that prevents IA to save data correctly.

**Comment by Mintycraft** [comment] 2020-04-10 00:14
![image](https://user-images.githubusercontent.com/52329037/78950891-0c128200-7a85-11ea-9f56-019eb41d4aaf.png)
This is the only other thing that comes up in console when any custom blocks are placed and removed, and this didn't even show up until 2.0.9. It happens every ten seconds or so if any blocks were placed or removed in that time period. Itemsadder isn't showing any errors. I don't know if /iareload itself was the issue to begin with, I just knew that was the easiest way to reproduce the error at the time.

**Comment by LoneDev6** [comment] 2020-04-14 13:26
I think it's related to this: https://github.com/LoneDev6/ItemsAdder/issues/127

Seems plugin is trying to save same region file at the same time (which is not possible and it fails), I'll try to reproduce the issue today and fix it!


Thanks a lot for the info

**Comment by LoneDev6** [comment] 2020-04-14 14:23
https://github.com/LoneDev6/ItemsAdder/issues/127#issuecomment-613473417

**Comment by LoneDev6** [comment] 2020-05-05 12:19
Is this still a problem? Just to make sure since 3 weeks passed, thanks!
I don't want to forget about anyone, so that's why I ask before I close the issue

**Comment by LoneDev6** [comment] 2020-05-18 22:10
Closed due to inactivity, reopen this if you still need help. 
Thanks :D

**Closed by LoneDev6** 2020-05-18 22:10 UTC
Labels: bug

**Comment by Mintycraft** [comment] 2020-10-28 19:49
Super sorry for never responding, but yes the issue has long since been resolved. Thank you very much,

**Comment by LoneDev6** [comment] 2020-10-29 20:44
No need to be sorry! Have a nice day
