### ISSUE TITLE
[BUG] Duplication with renamed items

### ISSUE THREAD

**Issue by canissorion** [LoneDev6/ItemsAdder#172] opened 2020-04-25 00:01 UTC
When a renamed item is used to craft something it returns the duplicate object and the duplicate renamed item x99999

**To Reproduce**
It happen with any craft in this case im gonna use Fire Sword
1. Go to 'Anvil rename a blaze rod x64'
2. Go to 'Crafting Table do the fire sword with a stack of renamed blaze rod  and a two stack of blaze powder'
3. Shift click the sword

 - Server version: paper 1.14.4
 - Client version: vanilla 1.14.4
 - Plugin version: 2.0.13

**Comment by canissorion** [comment] 2020-04-25 00:50
<img width="748" alt="Captura de Pantalla 2020-04-24 a la(s) 19 57 56" src="https://user-images.githubusercontent.com/33471737/80267035-192a9600-866d-11ea-98d2-9ef79de3a101.png">
<img width="801" alt="Captura de Pantalla 2020-04-24 a la(s) 19 58 06" src="https://user-images.githubusercontent.com/33471737/80267036-1cbe1d00-866d-11ea-930e-1f88d2c47a90.png">

**Comment by LoneDev6** [comment] 2020-04-28 17:08
Thanks, should be fixed in next update.
I will publish the update later, reopen this issue if the problem is still there after 2.0.14

**Closed by LoneDev6** 2020-04-28 17:08 UTC
Labels: bug
