### ISSUE TITLE
[BUG] Recipe result items do not update correctly in some cases

### ISSUE THREAD

**Issue by spathizilla** [LoneDev6/ItemsAdder#148] opened 2020-04-16 21:38 UTC
**Describe the bug**
Starting in 2.0.10, some vanilla items can sometimes be crafted with less items than necessary. I believe this is with vanilla items where a custom item is using the underlying vanilla item (eg sticks, leather armor, etc). For example I am able to craft sticks with a single plank rather than the double. 

I have verified this is **NOT** possible in 2.0.9

**To Reproduce**
1. Get 2 spruce planks
2. Open workbench
3. Place one plank in the bottom middle slot (see button displayed as result)
4. Place one plank in the central slot (result is updated to sticks)
5. Remove bottom middle plank from slot 

**Expected behavior**
Resulting item should update back to the button but sometimes remains as stick.
Click sticks and obtain them for the cost of 1 plank

![recipe](https://user-images.githubusercontent.com/638845/79508643-d267eb00-8031-11ea-96e2-3f5a1b944525.png)

This can also be achieved with diamond pickaxes for the cost of one diamond rather than three.
**To Reproduce**
1. Get three diamonds and two sticks
2. Open workbench
3. Place stick in bottom and middle slot
4. Place three diamonds across top - See pickaxe displayed (sometimes this glitches)
5. Shift left click the top left and top right diamond - Pickaxe remains displayed

**Expected behavior**
Resulting item should update back to a diamond shovel but stays as diamond pick.
Click diamond pick and obtain for cost of one diamond two sticks. This is a real item and survives over reconnects. 

![diamonds](https://user-images.githubusercontent.com/638845/79508640-d1cf5480-8031-11ea-902d-b88f166e7a20.png)

CMI: 8.6.22.2 BungeeCord
Server version: Paper(185) 1.15.2-R0.1-SNAPSHOT
Vault version: 1.7.3-b

[PlugMan] Plugin Information: ItemsAdder
- Version: 2.0.10
- Author(s): LoneDev, LoneDev
- Status: Enabled
- Depends: IALibs, ProtocolLib

**Comment by RustyDagger** [comment] 2020-04-17 00:26
a little similar to my could not pass error #141 but that was being caused by the plugin not getting the event when some one clicked on their 2x2 in their inventory. 

Sadly I recently purchased the plugin so I am unable to go back a version to test if that fixes my issue.

This issue seems like its not getting the clicks when you remove an item. does it do it when you use a recipe that only has IA items?

**Comment by LoneDev6** [comment] 2020-04-17 12:16
Fixed in 2.0.11, reopen this issue if after update you still have problems. I will post the update today.
Thanks for the report.

**Closed by LoneDev6** 2020-04-17 12:16 UTC
Labels: bug
